export default {
    'nb': {
        'boligpanel.bostotte': 'Bostøtte',
        'boligpanel.husbanken.url': 'http://www.husbanken.no/bostotte/',
        'boligpanel.husbanken': 'Husbanken',
        'boligpanel.kommunal': 'Leie eller eie bolig',
        'boligpanel.leie_eie.url': 'https://www.nav.no/no/Person/Flere+tema/Sosiale+tjenester/leie-eller-eie-bolig',
        'boligpanel.midlertidig_botilbud.url': 'https://www.nav.no/no/Person/Flere+tema/Sosiale+tjenester/bolig/midlertidig-botilbud',
        'boligpanel.midlertidig': 'Midlertidig botilbud',
        'boligpanel.situasjon': 'Nødsituasjon',
        'boligpanel.tittel': 'Hjelp til bolig',
        'feilside.tekst': 'Siden eller tjenesten finnes ikke eller er for tiden utilgjengelig. Vi beklager dette. Prøv igjen senere.',
        'feilside.tittel': 'Oops, noe gikk galt.',
        'forside.banner.bilde_alt': 'Grafisk figur av brukers møte med veileder.',
        'forside.banner.ingress': 'Vi viser deg også andre muligheter.',
        'forside.banner.tittel': 'Økonomisk sosialhjelp',
        'forside.finnjobber.tekst': 'Det du trenger for å komme i gang med å søke jobber',
        'forside.finnjobber.tittel': 'Finn og søk jobb',
        'forside.finnjobber.url': 'https://tjenester.nav.no/veiledearbeidssoker/?sprak=nb',
        'forside.jobblyst.tekst': 'Råd og veiledning for deg som er ung og har spørsmål om jobb og utdanning.',
        'forside.jobblyst.tittel': 'Jobblyst på Facebook',
        'forside.jobblyst.url': 'https://www.facebook.com/navjobblyst/',
        'forside.kontakte.nav.lenken.gjeld.chat.url': '<a href="https://www.nav.no/no/Person/Flere+tema/Sosiale+tjenester/Relatert+innhold/chat-med-oss-om-%C3%B8konomiske-problemer">Du kan også chatte med oss</a>',
        'forside.kontakte.nav.lenken.gjeld.ring.til': 'Ring NAV Gjeldsrådgivning',
        'forside.kontakte.nav.lenken.gjeld.ring.tlfnr': '<a href="tel:+4755553339">55 55 33 39</a>',
        'forside.kontakte.nav.lenken.gjeld.tittel': 'Har du økonomiske problemer',
        'forside.kontakte.nav.lenken.utgifter.radgivning.url': '<a href="https://www.nav.no/no/Person/Flere+tema/Sosiale+tjenester/Økonomisk-rådgivning-og-gjeldsrådgivning--87499">Økonomisk rådgivning og gjeldsrådgivning</a>',
        'forside.kontakte.nav.lenken.utgifter.redusere.url': '<a href="https://tjenester.nav.no/veiledearbeidssoker/mistet-jobben/okonomi-oversikt?sprak=nb">Hvordan kan du redusere utgiftene dine</a>',
        'forside.kontakte.nav.lenken.utgifter.tittel': 'Les om',
        'forside.lenkepanel.soke.tekst': 'Livsopphold, boutgifter, helse- og tannbehandling',
        'forside.lenkepanel.soke.tittel': 'Dette kan du søke om',
        'forside.lenkepanel.vite.tekst': 'Før du søker, når du søker og etter at du har søkt',
        'forside.lenkepanel.vite.tittel': 'Slik søker du',
        'forside.seksjon.andremuligheter.tittel': 'Andre muligheter',
        'kommunesok.feilmelding': 'Du må velge en kommune før du kan gå videre.',
        'kommunesok.tekst': 'Sjekk om du kan søke digitalt i din kommune.',
        'kommunesok.soknad_ikke_tilgjengelig': 'Du kan dessverre ikke søke digitalt i {kommuneNavn} kommune. Ta kontakt med <a href="{dittNavUrl}">NAV-kontoret ditt</a> for å få papirskjema.',
        'kommunesok.soknad_tilgjengelig': 'Du kan søke digitalt i {kommuneNavn} kommune. Hvis du ikke har penger til det aller mest nødvendige, som mat, bør du <a href="{dittNavUrl}">kontakte NAV-kontoret ditt</a> før du sender inn søknaden.',
        'kommunesok.placeholder': 'Søk etter kommune',
        'navigering.tilbake': 'Tilbake',
        'sok.digitalt': 'Søk digitalt',
        'sok.digitalt.en': 'Apply digitally',
        'sok.digitalt.nn': 'Søk digitalt',
        'sok.digitalt.no': 'Søk digitalt',
        'sok.digitalt.se': 'Søk digitalt',
        'sprak.engelsk': 'English',
        'sprak.norsk.bokmal': 'Bokmål',
        'sprak.norsk': 'Norsk',
        'sprak.nynorsk': 'Nynorsk',
        'sprak.samisk': 'Sámegiella',
        'sprak.sprakvalg.innhold': 'Språkvalg for innhold',
        'sprak.sprak': 'Language',
    },
    'nn': {
        'forside.banner.tittel': 'Økonomisk sosialhjelp',
        'kommunesok.tekst': 'Sjekk om du kan søkje digitalt i din kommune.',
        'kommunesok.feilmelding': 'Du må velge en kommune før du kan gå vidare.',
        'kommunesok.soknad_ikke_tilgjengelig': 'Du kan dessverre ikkje søkje digitalt i {kommuneNavn} kommune. Ta kontakt med <a href="{dittNavUrl}">NAV-kontoret ditt</a> for å få papirskjema.',
        'kommunesok.soknad_tilgjengelig': 'Du kan søkje digitalt i {kommuneNavn} kommune. Hvis du ikkje har pengar til det aller mest naudsynte, som mat, bør du <a href="{dittNavUrl}">kontakte kontakte NAV-kontoret</a> ditt før du sendar inn søknaden.',
        'sok.digitalt': 'Søk digitalt',
        'kommunesok.placeholder': 'Søk etter kommune',
        'sprak.sprakvalg.innhold': 'Språkvalg for innhold',
        'sprak.sprak': 'Language',
        'sprak.engelsk': 'English',
        'sprak.norsk.bokmal': 'Bokmål',
        'sprak.norsk': 'Norsk',
        'sprak.nynorsk': 'Nynorsk',
        'sprak.samisk': 'Sámegiella',

        'boligpanel.bostotte': 'Bostøtte',
        'boligpanel.husbanken.url': 'http://www.husbanken.no/bostotte/',
        'boligpanel.husbanken': 'Husbanken',
        'boligpanel.kommunal': 'Leie eller eie bolig',
        'boligpanel.leie_eie.url': 'https://www.nav.no/no/Person/Flere+tema/Sosiale+tjenester/leie-eller-eie-bolig',
        'boligpanel.midlertidig_botilbud.url': 'https://www.nav.no/no/Person/Flere+tema/Sosiale+tjenester/bolig/midlertidig-botilbud',
        'boligpanel.midlertidig': 'Midlertidig botilbud',
        'boligpanel.situasjon': 'Nødsituasjon',
        'boligpanel.tittel': 'Hjelp til bolig',
        'feilside.tekst': 'Siden eller tjenesten finnes ikke eller er for tiden utilgjengelig. Vi beklager dette. Prøv igjen senere.',
        'feilside.tittel': 'Oops, noe gikk galt.',
        'forside.banner.bilde_alt': 'Grafisk figur av brukers møte med veileder.',
        'forside.banner.ingress': 'Vi viser deg også andre muligheter.',
        'forside.finnjobber.tekst': 'Det du trenger for å komme i gang med å søke jobber',
        'forside.finnjobber.tittel': 'Finn og søk jobb',
        'forside.finnjobber.url': 'https://tjenester.nav.no/veiledearbeidssoker/?sprak=nb',
        'forside.jobblyst.tekst': 'Råd og veiledning for deg som er ung og har spørsmål om jobb og utdanning.',
        'forside.jobblyst.tittel': 'Jobblyst på Facebook',
        'forside.jobblyst.url': 'https://www.facebook.com/navjobblyst/',
        'forside.kontakte.nav.lenken.gjeld.chat.url': '<a href="https://www.nav.no/no/Person/Flere+tema/Sosiale+tjenester/Relatert+innhold/chat-med-oss-om-%C3%B8konomiske-problemer">Du kan også chatte med oss</a>',
        'forside.kontakte.nav.lenken.gjeld.ring.til': 'Ring NAV Gjeldsrådgivning',
        'forside.kontakte.nav.lenken.gjeld.ring.tlfnr': '<a href="tel:+4755553339">55 55 33 39</a>',
        'forside.kontakte.nav.lenken.gjeld.tittel': 'Har du økonomiske problemer',
        'forside.kontakte.nav.lenken.utgifter.radgivning.url': '<a href="https://www.nav.no/no/Person/Flere+tema/Sosiale+tjenester/Økonomisk-rådgivning-og-gjeldsrådgivning--87499">Økonomisk rådgivning og gjeldsrådgivning</a>',
        'forside.kontakte.nav.lenken.utgifter.redusere.url': '<a href="https://tjenester.nav.no/veiledearbeidssoker/mistet-jobben/okonomi-oversikt?sprak=nb">Hvordan kan du redusere utgiftene dine</a>',
        'forside.kontakte.nav.lenken.utgifter.tittel': 'Les om',
        'forside.lenkepanel.soke.tekst': 'Livsopphold, boutgifter, helse- og tannbehandling',
        'forside.lenkepanel.soke.tittel': 'Dette kan du søke om',
        'forside.lenkepanel.vite.tekst': 'Før du søker, når du søker og etter at du har søkt',
        'forside.lenkepanel.vite.tittel': 'Slik søker du',
        'forside.seksjon.andremuligheter.tittel': 'Andre muligheter',
        'navigering.tilbake': 'Tilbake',
        'sok.digitalt.en': 'Apply digitally',
        'sok.digitalt.nn': 'Søk digitalt',
        'sok.digitalt.no': 'Søk digitalt',
        'sok.digitalt.se': 'Søk digitalt',

    },
    'en': {
        'forside.banner.tittel': 'Financial assistance',
        'kommunesok.tekst': 'Check to see if you can apply digitally on municipality.',
        'kommunesok.feilmelding': 'You must first choose a municipality before continuing.',
        'kommunesok.soknad_ikke_tilgjengelig': 'You can\'t apply digitally in {kommuneNavn} municipality. Please <a href="{dittNavUrl}">contact your NAV-office</a> for application.',
        'kommunesok.soknad_tilgjengelig': 'You can apply digitally in {kommuneNavn} municipality. If you do not have sufficient funds for bare necessities, like food, you should <a href="{dittNavUrl}">contact your NAV-office</a> before sending the application.',
        'sok.digitalt': 'Apply digitally',
        'kommunesok.placeholder': 'Search for municipality',
        'sprak.sprakvalg.innhold': 'Språkvalg for innhold',
        'sprak.sprak': 'Language',
        'sprak.engelsk': 'English',
        'sprak.norsk.bokmal': 'Bokmål',
        'sprak.norsk': 'Norsk',
        'sprak.nynorsk': 'Nynorsk',
        'sprak.samisk': 'Sámegiella',
        'boligpanel.bostotte': 'Bostøtte',
        'boligpanel.husbanken.url': 'http://www.husbanken.no/bostotte/',
        'boligpanel.husbanken': 'Husbanken',
        'boligpanel.kommunal': 'Leie eller eie bolig',
        'boligpanel.leie_eie.url': 'https://www.nav.no/no/Person/Flere+tema/Sosiale+tjenester/leie-eller-eie-bolig',
        'boligpanel.midlertidig_botilbud.url': 'https://www.nav.no/no/Person/Flere+tema/Sosiale+tjenester/bolig/midlertidig-botilbud',
        'boligpanel.midlertidig': 'Midlertidig botilbud',
        'boligpanel.situasjon': 'In case of emergency',
        'boligpanel.tittel': 'Hjelp til bolig',
        'feilside.tekst': 'Siden eller tjenesten finnes ikke eller er for tiden utilgjengelig. Vi beklager dette. Prøv igjen senere.',
        'feilside.tittel': 'Oops. Something went wrong.',
        'forside.banner.bilde_alt': 'Grafic illustration of a user and an advisor.',
        'forside.banner.ingress': 'As well as other possibilites.',
        'forside.finnjobber.tekst': 'Det du trenger for å komme i gang med å søke jobber',
        'forside.finnjobber.tittel': 'Finn og søk jobb',
        'forside.finnjobber.url': 'https://tjenester.nav.no/veiledearbeidssoker/?sprak=nb',
        'forside.jobblyst.tekst': 'Råd og veiledning for deg som er ung og har spørsmål om jobb og utdanning.',
        'forside.jobblyst.tittel': 'Jobblyst på Facebook',
        'forside.jobblyst.url': 'https://www.facebook.com/navjobblyst/',
        'forside.kontakte.nav.lenken.gjeld.chat.url': '<a href="https://www.nav.no/no/Person/Flere+tema/Sosiale+tjenester/Relatert+innhold/chat-med-oss-om-%C3%B8konomiske-problemer">Chat</a>',
        'forside.kontakte.nav.lenken.gjeld.ring.til': 'Call NAV debt counselling',
        'forside.kontakte.nav.lenken.gjeld.ring.tlfnr': '<a href="tel:+4755553339">55 55 33 39</a>',
        'forside.kontakte.nav.lenken.gjeld.tittel': 'Are you in financial stress?',
        'forside.kontakte.nav.lenken.utgifter.radgivning.url': '<a href="https://www.nav.no/no/Person/Flere+tema/Sosiale+tjenester/Økonomisk-rådgivning-og-gjeldsrådgivning--87499">Økonomisk rådgivning og gjeldsrådgivning</a>',
        'forside.kontakte.nav.lenken.utgifter.redusere.url': '<a href="https://tjenester.nav.no/veiledearbeidssoker/mistet-jobben/okonomi-oversikt?sprak=nb">Hvordan kan du redusere utgiftene dine</a>',
        'forside.kontakte.nav.lenken.utgifter.tittel': 'More info',
        'forside.lenkepanel.soke.tekst': 'Livsopphold, boutgifter, helse- og tannbehandling',
        'forside.lenkepanel.soke.tittel': 'What can financial assistance cover',
        'forside.lenkepanel.vite.tekst': 'Før du søker, når du søker og etter at du har søkt',
        'forside.lenkepanel.vite.tittel': 'How to apply for financial assistance',
        'forside.seksjon.andremuligheter.tittel': 'Other possibilities',
        'navigering.tilbake': 'Back',
        'sok.digitalt.en': 'Apply digitally',
        'sok.digitalt.nn': 'Søk digitalt',
        'sok.digitalt.no': 'Søk digitalt',
        'sok.digitalt.se': 'Søk digitalt',
    }
};
